version: "3.9"
services: 
  app:
    container_name: app-container 
    image: thiagodz7/app-mongo:1.0
    networks:
      - app-sisaud-network
    ports:
      - "3000:3000"
    volumes: 
       - type: bind
         source: /root/appmongo/app/logs
         target: /usr/src/app/logs
    depends_on: 
      - mongo_db
  mongo_db:
     container_name: mongo-container
     image: thiagodz7/mongo
     networks:
       - app-sisaud-network
     ports:
       - 27017:27017
     environment:
        MONGO_INITDB_ROOT_USERNAME: adm
        MONGO_DATABASE: usuario
        MONGO_USER: adm
        MONGO_INITDB_ROOT_PASSWORD: 123
     volumes:
         - type: bind
           source: /root/appmongo/mongo/mongo-volumes
           target: /var/lib/mongo
networks:
  app-sisaud-network:
    driver: bridge
       
     
